### PR TITLE
Adds API events

### PR DESCRIPTION
**Pull request by HealPotion**
The developer could listen to the StackKilledEvent to get the killer player and the number of entities killed.

### CODE REVIEW

**Comment by Nathat23** [comment]
Your code doesn't work when kill-step or single killing methods are used.

**Comment by HealPotion** [comment]
I thought kill-step or single killing can be handled by bukkit EntityDeathEvent. Wouldn't it be duplicate to add it?

**Comment by Nathat23** [comment]
no, because using the event from this plugin you know that the entity has been stacked.

**Comment by HealPotion** [comment]
I think that fixes it.

**Pull request closed without merging**
