### PR TITLE
Project cleanup

### PR DESCRIPTION
**Pull request by sgdc3**

### CODE REVIEW

**Comment by sgdc3** [comment]
Oh no, could you force reset your repository? xD

**Comment by sgdc3** [comment]
Just run "git reset --hard b8ed8f7f39c2196ab5e1267b2d8dcf95c112f9e7" and "git push -f"

**Comment by sgdc3** [comment]
Ok, now you can merge this :)

**Comment by sgdc3** [comment]
Ok, looking into it ;)

What do you mean with breaks the reload command?

**Comment by sgdc3** [comment]
Rip conflicts

**Comment by sgdc3** [comment]
@Nathat23 Fixed, but it conflicts with your changes, could you reset again and merge?

**Comment by LogGits** [comment]
@sgdc3 How is progress going with this?

**Comment by sgdc3** [comment]
Abbandoned atm, i'm sorry

**Pull request closed without merging**
